# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\dropbox\dokumente\pi3\code\python\qutip_enhanced\qutip_enhanced/qtgui/plot_data.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(1673, 998)
        self.parameter_tab = QtWidgets.QTabWidget(window)
        self.parameter_tab.setGeometry(QtCore.QRect(30, 0, 1641, 1001))
        self.parameter_tab.setObjectName("parameter_tab")
        self.plot_tab = QtWidgets.QWidget()
        self.plot_tab.setObjectName("plot_tab")
        self.observation_widget = QtWidgets.QListWidget(self.plot_tab)
        self.observation_widget.setGeometry(QtCore.QRect(1300, 0, 331, 261))
        self.observation_widget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.observation_widget.setObjectName("observation_widget")
        self.parameter_table = QTableWidgetEnhancedDrop(self.plot_tab)
        self.parameter_table.setGeometry(QtCore.QRect(0, 0, 1291, 261))
        self.parameter_table.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.parameter_table.setObjectName("parameter_table")
        self.parameter_table.setColumnCount(0)
        self.parameter_table.setRowCount(0)
        self.gridLayoutWidget = QtWidgets.QWidget(self.plot_tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 270, 1391, 631))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.plot_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.plot_layout.setContentsMargins(0, 0, 0, 0)
        self.plot_layout.setObjectName("plot_layout")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.plot_tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 900, 1391, 71))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.toolbar_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.toolbar_layout.setContentsMargins(0, 0, 0, 0)
        self.toolbar_layout.setObjectName("toolbar_layout")
        self.update_plot_button = QtWidgets.QPushButton(self.plot_tab)
        self.update_plot_button.setGeometry(QtCore.QRect(1400, 270, 231, 51))
        self.update_plot_button.setObjectName("update_plot_button")
        self.x_axis_parameter_comboBox = QtWidgets.QComboBox(self.plot_tab)
        self.x_axis_parameter_comboBox.setGeometry(QtCore.QRect(1400, 350, 231, 22))
        self.x_axis_parameter_comboBox.setEditable(False)
        self.x_axis_parameter_comboBox.setMaxVisibleItems(30)
        self.x_axis_parameter_comboBox.setFrame(True)
        self.x_axis_parameter_comboBox.setObjectName("x_axis_parameter_comboBox")
        self.label = QtWidgets.QLabel(self.plot_tab)
        self.label.setGeometry(QtCore.QRect(1400, 330, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Panel)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setObjectName("label")
        self.open_explorer_button = QtWidgets.QPushButton(self.plot_tab)
        self.open_explorer_button.setGeometry(QtCore.QRect(1400, 928, 231, 41))
        self.open_explorer_button.setObjectName("open_explorer_button")
        self.open_code_button = QtWidgets.QPushButton(self.plot_tab)
        self.open_code_button.setGeometry(QtCore.QRect(1400, 880, 231, 41))
        self.open_code_button.setObjectName("open_code_button")
        self.info = QtWidgets.QPlainTextEdit(self.plot_tab)
        self.info.setGeometry(QtCore.QRect(1400, 380, 231, 491))
        self.info.setAcceptDrops(False)
        self.info.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.info.setReadOnly(True)
        self.info.setBackgroundVisible(False)
        self.info.setObjectName("info")
        self.parameter_table.raise_()
        self.observation_widget.raise_()
        self.gridLayoutWidget.raise_()
        self.gridLayoutWidget_2.raise_()
        self.update_plot_button.raise_()
        self.x_axis_parameter_comboBox.raise_()
        self.label.raise_()
        self.open_explorer_button.raise_()
        self.open_code_button.raise_()
        self.info.raise_()
        self.parameter_tab.addTab(self.plot_tab, "")
        self.fit_tab = QtWidgets.QWidget()
        self.fit_tab.setObjectName("fit_tab")
        self.fit_select_table = QTableWidgetEnhanced(self.fit_tab)
        self.fit_select_table.setGeometry(QtCore.QRect(0, 0, 1081, 261))
        self.fit_select_table.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.fit_select_table.setObjectName("fit_select_table")
        self.fit_select_table.setColumnCount(0)
        self.fit_select_table.setRowCount(0)
        self.fit_result_table = QTableWidgetEnhanced(self.fit_tab)
        self.fit_result_table.setGeometry(QtCore.QRect(1090, 0, 661, 261))
        self.fit_result_table.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.fit_result_table.setObjectName("fit_result_table")
        self.fit_result_table.setColumnCount(0)
        self.fit_result_table.setRowCount(0)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.fit_tab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 900, 1391, 71))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.toolbar_fit_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.toolbar_fit_layout.setContentsMargins(0, 0, 0, 0)
        self.toolbar_fit_layout.setObjectName("toolbar_fit_layout")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.fit_tab)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 270, 1391, 631))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.plot_fit_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.plot_fit_layout.setContentsMargins(0, 0, 0, 0)
        self.plot_fit_layout.setObjectName("plot_fit_layout")
        self.update_fit_result_button = QtWidgets.QPushButton(self.fit_tab)
        self.update_fit_result_button.setGeometry(QtCore.QRect(1400, 270, 231, 111))
        self.update_fit_result_button.setObjectName("update_fit_result_button")
        self.parameter_tab.addTab(self.fit_tab, "")
        self.dataframe_tab = QtWidgets.QWidget()
        self.dataframe_tab.setObjectName("dataframe_tab")
        self.dataframe = DataFrameWidget(self.dataframe_tab)
        self.dataframe.setGeometry(QtCore.QRect(-5, 1, 1761, 981))
        self.dataframe.setObjectName("dataframe")
        self.parameter_tab.addTab(self.dataframe_tab, "")

        self.retranslateUi(window)
        self.parameter_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "Form"))
        self.update_plot_button.setText(_translate("window", "UpdatePlot"))
        self.label.setText(_translate("window", "x-axis parameter"))
        self.open_explorer_button.setText(_translate("window", "Open Explorer Window"))
        self.open_code_button.setText(_translate("window", "Measurement Code"))
        self.parameter_tab.setTabText(self.parameter_tab.indexOf(self.plot_tab), _translate("window", "Plot"))
        self.update_fit_result_button.setText(_translate("window", "UpdateFit"))
        self.parameter_tab.setTabText(self.parameter_tab.indexOf(self.fit_tab), _translate("window", "Fit"))
        self.parameter_tab.setTabText(self.parameter_tab.indexOf(self.dataframe_tab), _translate("window", "DataFrame"))

from qutip_enhanced.qtgui.custom_widgets import DataFrameWidget, QTableWidgetEnhanced, QTableWidgetEnhancedDrop
