# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\qutip_enhanced\qutip_enhanced\qtgui\plot_data.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(717, 809)
        self.gridLayout_4 = QtWidgets.QGridLayout(window)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.parameter_tab = QtWidgets.QTabWidget(window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameter_tab.sizePolicy().hasHeightForWidth())
        self.parameter_tab.setSizePolicy(sizePolicy)
        self.parameter_tab.setTabPosition(QtWidgets.QTabWidget.North)
        self.parameter_tab.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.parameter_tab.setDocumentMode(True)
        self.parameter_tab.setMovable(False)
        self.parameter_tab.setObjectName("parameter_tab")
        self.plot_tab = QtWidgets.QWidget()
        self.plot_tab.setObjectName("plot_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.plot_tab)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.update_plot_button = QtWidgets.QPushButton(self.plot_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update_plot_button.sizePolicy().hasHeightForWidth())
        self.update_plot_button.setSizePolicy(sizePolicy)
        self.update_plot_button.setMaximumSize(QtCore.QSize(250, 16777215))
        self.update_plot_button.setObjectName("update_plot_button")
        self.verticalLayout_3.addWidget(self.update_plot_button)
        self.label = QtWidgets.QLabel(self.plot_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Panel)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.x_axis_parameter_comboBox = QtWidgets.QComboBox(self.plot_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_axis_parameter_comboBox.sizePolicy().hasHeightForWidth())
        self.x_axis_parameter_comboBox.setSizePolicy(sizePolicy)
        self.x_axis_parameter_comboBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.x_axis_parameter_comboBox.setEditable(False)
        self.x_axis_parameter_comboBox.setMaxVisibleItems(30)
        self.x_axis_parameter_comboBox.setFrame(True)
        self.x_axis_parameter_comboBox.setObjectName("x_axis_parameter_comboBox")
        self.verticalLayout_3.addWidget(self.x_axis_parameter_comboBox)
        self.label_2 = QtWidgets.QLabel(self.plot_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.col_ax_parameter_comboBox = QtWidgets.QComboBox(self.plot_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.col_ax_parameter_comboBox.sizePolicy().hasHeightForWidth())
        self.col_ax_parameter_comboBox.setSizePolicy(sizePolicy)
        self.col_ax_parameter_comboBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.col_ax_parameter_comboBox.setEditable(False)
        self.col_ax_parameter_comboBox.setMaxVisibleItems(30)
        self.col_ax_parameter_comboBox.setFrame(True)
        self.col_ax_parameter_comboBox.setObjectName("col_ax_parameter_comboBox")
        self.verticalLayout_3.addWidget(self.col_ax_parameter_comboBox)
        self.label_4 = QtWidgets.QLabel(self.plot_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.row_ax_parameter_comboBox = QtWidgets.QComboBox(self.plot_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.row_ax_parameter_comboBox.sizePolicy().hasHeightForWidth())
        self.row_ax_parameter_comboBox.setSizePolicy(sizePolicy)
        self.row_ax_parameter_comboBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.row_ax_parameter_comboBox.setEditable(False)
        self.row_ax_parameter_comboBox.setMaxVisibleItems(30)
        self.row_ax_parameter_comboBox.setFrame(True)
        self.row_ax_parameter_comboBox.setObjectName("row_ax_parameter_comboBox")
        self.verticalLayout_3.addWidget(self.row_ax_parameter_comboBox)
        self.label_3 = QtWidgets.QLabel(self.plot_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.subtract_parameter_comboBox = QtWidgets.QComboBox(self.plot_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subtract_parameter_comboBox.sizePolicy().hasHeightForWidth())
        self.subtract_parameter_comboBox.setSizePolicy(sizePolicy)
        self.subtract_parameter_comboBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.subtract_parameter_comboBox.setEditable(False)
        self.subtract_parameter_comboBox.setMaxVisibleItems(30)
        self.subtract_parameter_comboBox.setFrame(True)
        self.subtract_parameter_comboBox.setObjectName("subtract_parameter_comboBox")
        self.verticalLayout_3.addWidget(self.subtract_parameter_comboBox)
        self.info = QtWidgets.QPlainTextEdit(self.plot_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info.sizePolicy().hasHeightForWidth())
        self.info.setSizePolicy(sizePolicy)
        self.info.setMaximumSize(QtCore.QSize(250, 16777215))
        self.info.setAcceptDrops(False)
        self.info.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.info.setReadOnly(True)
        self.info.setBackgroundVisible(False)
        self.info.setObjectName("info")
        self.verticalLayout_3.addWidget(self.info)
        self.open_code_button = QtWidgets.QPushButton(self.plot_tab)
        self.open_code_button.setMaximumSize(QtCore.QSize(250, 16777215))
        self.open_code_button.setObjectName("open_code_button")
        self.verticalLayout_3.addWidget(self.open_code_button)
        self.open_explorer_button = QtWidgets.QPushButton(self.plot_tab)
        self.open_explorer_button.setMaximumSize(QtCore.QSize(250, 16777215))
        self.open_explorer_button.setObjectName("open_explorer_button")
        self.verticalLayout_3.addWidget(self.open_explorer_button)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.plot_layout = QtWidgets.QGridLayout()
        self.plot_layout.setObjectName("plot_layout")
        self.verticalLayout_5.addLayout(self.plot_layout)
        self.toolbar_layout = QtWidgets.QGridLayout()
        self.toolbar_layout.setContentsMargins(-1, -1, 0, -1)
        self.toolbar_layout.setObjectName("toolbar_layout")
        self.verticalLayout_5.addLayout(self.toolbar_layout)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.observation_widget = QtWidgets.QListWidget(self.plot_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.observation_widget.sizePolicy().hasHeightForWidth())
        self.observation_widget.setSizePolicy(sizePolicy)
        self.observation_widget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.observation_widget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.observation_widget.setObjectName("observation_widget")
        self.gridLayout_2.addWidget(self.observation_widget, 0, 1, 1, 1)
        self.parameter_table = QTableWidgetEnhancedDrop(self.plot_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameter_table.sizePolicy().hasHeightForWidth())
        self.parameter_table.setSizePolicy(sizePolicy)
        self.parameter_table.setMaximumSize(QtCore.QSize(16777215, 300))
        self.parameter_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.parameter_table.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.parameter_table.setObjectName("parameter_table")
        self.parameter_table.setColumnCount(0)
        self.parameter_table.setRowCount(0)
        self.gridLayout_2.addWidget(self.parameter_table, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.parameter_tab.addTab(self.plot_tab, "")
        self.fit_tab = QtWidgets.QWidget()
        self.fit_tab.setObjectName("fit_tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.fit_tab)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.fit_result_table = QTableWidgetEnhanced(self.fit_tab)
        self.fit_result_table.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.fit_result_table.setObjectName("fit_result_table")
        self.fit_result_table.setColumnCount(0)
        self.fit_result_table.setRowCount(0)
        self.gridLayout_6.addWidget(self.fit_result_table, 0, 0, 1, 1)
        self.update_fit_result_button = QtWidgets.QPushButton(self.fit_tab)
        self.update_fit_result_button.setObjectName("update_fit_result_button")
        self.gridLayout_6.addWidget(self.update_fit_result_button, 1, 1, 1, 1)
        self.fit_select_table = QTableWidgetEnhanced(self.fit_tab)
        self.fit_select_table.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.fit_select_table.setObjectName("fit_select_table")
        self.fit_select_table.setColumnCount(0)
        self.fit_select_table.setRowCount(0)
        self.gridLayout_6.addWidget(self.fit_select_table, 2, 0, 1, 1)
        self.plot_fit_layout = QtWidgets.QGridLayout()
        self.plot_fit_layout.setObjectName("plot_fit_layout")
        self.gridLayout_6.addLayout(self.plot_fit_layout, 3, 0, 1, 1)
        self.toolbar_fit_layout = QtWidgets.QGridLayout()
        self.toolbar_fit_layout.setContentsMargins(-1, -1, 0, -1)
        self.toolbar_fit_layout.setObjectName("toolbar_fit_layout")
        self.gridLayout_6.addLayout(self.toolbar_fit_layout, 4, 0, 1, 1)
        self.parameter_tab.addTab(self.fit_tab, "")
        self.gridLayout_4.addWidget(self.parameter_tab, 0, 0, 1, 1)

        self.retranslateUi(window)
        self.parameter_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "Form"))
        self.update_plot_button.setText(_translate("window", "UpdatePlot"))
        self.label.setText(_translate("window", "x-axis parameter"))
        self.label_2.setText(_translate("window", "col_ax_parameter"))
        self.label_4.setText(_translate("window", "row_ax_parameter"))
        self.label_3.setText(_translate("window", "subtract_parameter"))
        self.open_code_button.setText(_translate("window", "Measurement Code"))
        self.open_explorer_button.setText(_translate("window", "Open Explorer Window"))
        self.parameter_tab.setTabText(self.parameter_tab.indexOf(self.plot_tab), _translate("window", "Plot"))
        self.update_fit_result_button.setText(_translate("window", "UpdateFit"))
        self.parameter_tab.setTabText(self.parameter_tab.indexOf(self.fit_tab), _translate("window", "Fit"))

from qutip_enhanced.qtgui.custom_widgets import QTableWidgetEnhanced, QTableWidgetEnhancedDrop
